routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('dashboard'));
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('d/quiz', QuizController::class);

Route::resource('d/section', SectionController::class);

Route::resource('d/question', QuestionController::class);

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    protected $fillable = [
        'quiz_id',
        'section_id',
        'title',
        'type',
        'options',
        'answer'
    ];

    public function quiz()
    {
        return $this->belongsTo(Quiz::class, 'quiz_id');
    }

    public function section()
    {
        return $this->belongsTo(Section::class, 'section_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quiz;
use App\Models\Section;
use App\Models\Question;
use Illuminate\Http\Request;


class QuestionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::paginate(20);
       return view('dashboard.question.index', [
           'questions' => $questions
       ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sections = Section::get()->all();
        $quizess = Quiz::get()->all();
        return view('dashboard.question.create', [
            'sections' => $sections,
            'quizess' => $quizess
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        //validation
        $request->validate([
            'title' => 'required|max:255',
            'type' => [function ($attribute, $value, $fail) {
                if( $value === 'single' || $value === 'multiple') {
                    return true;
                } else {
                    $fail($attribute.' is invalid.');
                }
            }],
            'quiz_id' => 'required|integer|gt:0',
            'section_id' => 'required|integer|gt:0'
        ]);
        //create object and save
        $question = Question::create([
            'quiz_id' => $request->quiz_id,
            'section_id' => $request->section_id,
            'title' => $request->title,
            'type' => $request->type,
            'options' => json_encode($request->options),
            'answer' => json_encode($request->answer),
        ]);
        //set flash & redirect
        if($question){
            session()->flash('success', 'Question is successfully created!'); 
            return redirect(route('question.index'));
        }
        else{
            session()->flash('error', 'Failed to create question!'); 
            return redirect(route('question.create'));
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        return view('dashboard.question.show', [
            'question' => $question
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $sections = Section::get()->all();
        $quizess = Quiz::get()->all();
        return view('dashboard.question.edit', [
            'sections' => $sections,
            'quizess' => $quizess,
            'question' => $question,
            'options' => (json_decode($question->options) == null)? [] : json_decode($question->options),
            'answer' => (json_decode($question->answer) == null)? [] : json_decode($question->answer)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        // dd($request->all());
        //validation
        $request->validate([
            'title' => 'required|max:255',
            'type' => [function ($attribute, $value, $fail) {
                if( $value === 'single' || $value === 'multiple') {
                    return true;
                } else {
                    $fail($attribute.' is invalid.');
                }
            }],
            'quiz_id' => 'required|integer|gt:0',
            'section_id' => 'required|integer|gt:0'
        ]);
        //update object and save
        $question->update([
            'quiz_id' => $request->quiz_id,
            'section_id' => $request->section_id,
            'title' => $request->title,
            'type' => $request->type,
            'options' => json_encode($request->options),
            'answer' => json_encode($request->answer),
        ]);

        //set flash & redirect
        if($question){
            session()->flash('success', 'Question is successfully updated!'); 
            return redirect(route('question.show', $question->id));
        }
        else{
            session()->flash('error', 'Failed to update question!'); 
            return redirect(route('question.edit', $question->id));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //delete question
        $question->delete();
        //set flash message
        session()->flash('success', 'Question is successfully deleted!'); 
        //redirect
        return redirect(route('question.index'));
    }
}

resources/views/dashboard/question/create.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add New Question</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-6">
            <div class="question-form">
                <form action="{{ route('question.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>Quiz</label>
                        <select class="form-control @error('quiz_id')is-invalid @enderror" id="questionSelectQuiz"
                            name="quiz_id">
                            <option>Select Quiz</option>
                            @foreach ($quizess as $quiz)
                            <option value="{{ $quiz->id }}">{{ $quiz->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Section</label>
                        <select class="form-control @error('section_id')is-invalid @enderror" id="questionSelectSection"
                            name="section_id">
                            <option>Select Section</option>
                            @foreach ($sections as $section)
                            <option value="{{ $section->id }}">{{ $section->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            questionInputTitle" name="title" value="{{ old('title') }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Question Type</label>
                        <select class="form-control @error('type')is-invalid @enderror" id="questionSelectType"
                            name="type" onchange="questionTypeChange(event.target.value)">
                            <option>Select Type</option>
                            <option value="single">Single</option>
                            <option value="multiple">Multiple</option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group option-fields">
                                <label>Options</label>
                                <input type="text" class="form-control mb-3" id="questionInputOption0" name="options[]"
                                    value="{{ old('options[0]') }}" placeholder="Option 1">
                                <input type="text" class="form-control mb-3" id="questionInputOption1" name="options[]"
                                    value="{{ old('options[1]') }}" placeholder="Option 2">
                                <input type="text" class="form-control mb-3" id="questionInputOption2" name="options[]"
                                    value="{{ old('options[2]') }}" placeholder="Option 3">
                                <input type="text" class="form-control mb-3" id="questionInputOption3" name="options[]"
                                    value="{{ old('options[3]') }}" placeholder="Option 4">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group answer-fields">
                                <label>Currect Answer</label>
                                <input type="radio" class="form-control mb-3" id="questionInputAnswer0" value="1"
                                    name="answer[]">
                                <input type="radio" class="form-control mb-3" id="questionInputAnswer1" value="2"
                                    name="answer[]">
                                <input type="radio" class="form-control mb-3" id="questionInputAnswer2" value="3"
                                    name="answer[]">
                                <input type="radio" class="form-control mb-3" id="questionInputAnswer3" value="4"
                                    name="answer[]">
                            </div>
                        </div>
                    </div>

                    <hr>
                    <button type="submit" class="btn btn-primary">Create</button>


                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    let optionFields = $('.option-fields');
    let answerFields = $('.answer-fields');
    let answerInput = $('.answer-fields input');
    let optionInput = $('.option-fields input');

    optionFields.hide();
    answerFields.hide();
    const questionTypeChange = (value) => {
        if(value === 'single'){
            optionFields.show();
            answerFields.show();
            answerInput.each(function(){
                $(this).attr('type', 'radio');
            });
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }else if(value === 'multiple'){
            optionFields.show();
            answerFields.show();
            answerInput.each(function(){
                $(this).attr('type', 'checkbox');
            });
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }else{
            optionFields.hide();
            answerFields.hide();
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }
    }
</script>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/question/edit.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit: {{ $question->title }}</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-6">
            <div class="question-form">
                <form action="{{ route('question.update', $question->id) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label>Quiz</label>
                        <select class="form-control @error('quiz_id')is-invalid @enderror" id="questionSelectQuiz"
                            name="quiz_id">
                            <option>Select Quiz</option>
                            @foreach ($quizess as $quiz)
                            <option @if($question->quiz_id === $quiz->id) selected @endif
                                value="{{ $quiz->id }}">{{ $quiz->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Section</label>
                        <select class="form-control @error('section_id')is-invalid @enderror" id="questionSelectSection"
                            name="section_id">
                            <option>Select Section</option>
                            @foreach ($sections as $section)
                            <option value="{{ $section->id }}" @if($question->section_id === $section->id) selected
                                @endif>{{ $section->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            questionInputTitle" name="title" value="{{ $question->title }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Question Type</label>
                        <select class="form-control @error('type')is-invalid @enderror" id="questionSelectType"
                            name="type" onchange="questionTypeChange(event.target.value)">
                            <option>Select Type</option>
                            <option @if($question->type === 'single') selected @endif value="single">Single</option>
                            <option @if($question->type === 'multiple') selected @endif value="multiple">Multiple
                            </option>
                        </select>
                    </div>
                    {{--  for radio & checkbox type questions  --}}

                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group option-fields">
                                <label>Options</label>
                                <input type="text" class="form-control mb-3" id="questionInputOption0" name="options[]"
                                    value="{{ $options ? $options[0] : '' }}" placeholder="Option 1">
                                <input type="text" class="form-control mb-3" id="questionInputOption1" name="options[]"
                                    value="{{ $options ? $options[1] : '' }}" placeholder="Option 2">
                                <input type="text" class="form-control mb-3" id="questionInputOption2" name="options[]"
                                    value="{{ $options ? $options[2] : '' }}" placeholder="Option 3">
                                <input type="text" class="form-control mb-3" id="questionInputOption3" name="options[]"
                                    value="{{ $options ? $options[3] : '' }}" placeholder="Option 4">
                            </div>
                        </div>
                        {{-- currect answer fields --}}
                        <div class="col-md-3">
                            <div class="form-group answer-fields">
                                <label class="d-block text-center">Currect Answer</label>
                                <input type="checkbox" class="form-control mb-3" id="questionInputAnswer0" value="1"
                                    name="answer[]" {{ in_array("1", $answer)? "checked" : "" }}>
                                <input type="checkbox" class="form-control mb-3" id="questionInputAnswer1" value="2"
                                    name="answer[]" {{ in_array("2", $answer)? "checked" : "" }}>
                                <input type="checkbox" class="form-control mb-3" id="questionInputAnswer2" value="3"
                                    name="answer[]" {{ in_array("3", $answer)? "checked" : "" }}>
                                <input type="checkbox" class="form-control mb-3" id="questionInputAnswer3" value="4"
                                    name="answer[]" {{ in_array("4", $answer)? "checked" : "" }}>

                            </div>
                        </div>
                    </div>


                    <hr>
                    <button type="submit" class="btn btn-primary">Update</button>


                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    let optionFields = $('.option-fields' );
    let answerFields = $('.answer-fields' );
    let answerInput = $('.answer-fields input' );
    let optionInput = $('.option-fields input' );
    let questionType = $('#questionSelectType' ).val();

    optionFields.hide();
    answerFields.hide();
    if(questionType === 'single'){
        optionFields.show();
        answerFields.show();
        answerInput.each(function(){
            $(this).attr('type', 'radio');
        });
    }
    else if(questionType === 'multiple'){
        optionFields.show();
        answerFields.show();
        answerInput.each(function(){
            $(this).attr('type', 'checkbox');
        });
    }else{
        optionFields.hide();
        answerFields.hide();
    } 
    const questionTypeChange = (value) => {
        if(value === 'single'){
            optionFields.show();
            answerFields.show();
            answerInput.each(function(){
                $(this).attr('type', 'radio');
            });
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }else if(value === 'multiple'){
            optionFields.show();
            answerFields.show();
            answerInput.each(function(){
                $(this).attr('type', 'checkbox');
            });
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }else{
            optionFields.hide();
            answerFields.hide();
            answerInput.each(function(){
                $(this).removeAttr('checked');
            });
            optionInput.each(function(){
                $(this).val('');
            });
        }
    }
</script>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/question/index.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Questions</h1>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            @if (count($questions) <= 0) <p>No question found.</p>
                @else
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Type</th>
                            <th scope="col">Quiz</th>
                            <th scope="col">Section</th>
                            <th scope="col">Created At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($questions as $index => $question)
                        <tr>
                            <th scope="row">{{ $index+1 }}</th>
                            <td>{{ $question->title }}</td>
                            <td>{{ $question->type }}</td>
                            <td>{{ $question->quiz->title }}</td>
                            <td>{{ $question->section->title }}</td>
                            <td>{{ date('F j, Y', strtotime($question->created_at)) }}</td>
                            <td class="d-flex">
                                <a href="{{ route('question.show', $question) }}" class="btn btn-sm btn-primary mr-2"><i
                                        class="fa fa-eye"> </i> View</a>
                                <a href="{{ route('question.edit', $question) }}" class="btn btn-sm btn-info mr-2"><i
                                        class="fa fa-pencil"> </i> Edit</a>
                                {{--  <a href="{{ route('question.destroy', $question) }}" class="btn btn-sm
                                btn-danger">Delete</a>
                                --}}
                                <form method="post" action="{{ route('question.destroy', $question) }}"
                                    class="form-inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                                        onclick="return confirm('Are you sure you want to delete this item?');"> <i
                                            class="fa fa-trash"> </i> Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $questions->links() }}
                @endif
        </div>
    </div>



</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/question/show.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $question->title }}</h1>
        <a href="{{ route('question.edit', $question->id) }}" class="btn btn-sm btn-info shadow-sm ml-auto"><i
                class="fa fa-pencil"></i> Edit</a>
        <form method="post" action="{{ route('question.destroy', $question) }}" class="form-inline ml-2">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                onclick="return confirm('Are you sure you want to delete this item?');"> <i class="fa fa-trash"> </i>
                Delete</button>
        </form>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="question-content">
                <p><strong>Quiz:</strong> {{ $question->quiz->title }}</p>

                <p><strong>Section:</strong> {{ $question->section->title }}</p>

                <p><strong>Type:</strong> {{ $question->type }}</p>

                <p><strong>Title:</strong> {{ $question->title }}</p>

                <p><strong>Options:</strong> </p>

                <ol>
                    @foreach (json_decode($question->options) as $option)
                    <li>{{ $option }}</li>
                    @endforeach
                </ol>

                <p><strong>Correct Answer: </strong>{{ implode(',',json_decode($question->answer)) }}</p>
            </div>
        </div>
    </div>


</div>
<!-- /.container-fluid -->
@endsection