routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('dashboard'));
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('d/quiz', QuizController::class);

Route::resource('d/section', SectionController::class);

Route::resource('d/question', QuestionController::class);

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
    ];

    public function getTitle(Section $section){
        return $section->title;
    }

    public function questions(){
        return $this->hasMany(Question::class, 'section_id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Section;
use Illuminate\Http\Request;


class SectionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sections = Section::paginate(20);
       return view('dashboard.section.index', [
           'sections' => $sections
       ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.section.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'title' => 'required|max:255',
        ]);
        //create object and save
        $section = Section::create([
            'title' => $request->title,
        ]);
        //set flash & redirect
        if($section){
            session()->flash('success', 'Section is successfully created!'); 
            return redirect(route('section.index'));
        }
        else{
            session()->flash('error', 'Failed to create section!'); 
            return redirect(route('section.create'));
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        // dd($section->questions);
        return view('dashboard.section.show', [
            'section' => $section,
            'questions' => $section->questions,

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        return view('dashboard.section.edit', [
            'section' => $section
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
        //validation
        $request->validate([
            'title' => 'required|max:255',
        ]);
        //update object and save
        $section->update([
                            'title' => $request->title,
                        ]);

        //set flash & redirect
        if($section){
            session()->flash('success', 'Section is successfully updated!'); 
            return redirect(route('section.show', $section->id));
        }
        else{
            session()->flash('error', 'Failed to update section!'); 
            return redirect(route('section.edit', $section->id));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        //delete section
        $section->delete();
        //set flash message
        session()->flash('success', 'Section is successfully deleted!'); 
        //redirect
        return redirect(route('section.index'));
    }
}

resources/views/dashboard/section/create.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add New Section</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-6">
            <div class="section-form">
                <form action="{{ route('section.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            sectionInputTitle" name="title" value="{{ old('title') }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-primary">Create</button>


                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/section/edit.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit: {{ $section->title }}</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-6">
            <div class="section-form">
                <form action="{{ route('section.update', $section->id) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            sectionInputTitle" name="title" value="{{ $section->title }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/section/index.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Section</h1>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            @if (count($sections) <= 0) <p>No section found.</p>
                @else
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Created At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($sections as $index => $section)
                        <tr>
                            <th scope="row">{{ $index+1 }}</th>
                            <td>{{ $section->title }}</td>
                            <td>{{ date('F j, Y', strtotime($section->created_at)) }}</td>
                            <td class="d-flex">
                                <a href="{{ route('section.show', $section) }}" class="btn btn-sm btn-primary mr-2"><i
                                        class="fa fa-eye"></i> View</a>
                                <a href="{{ route('section.edit', $section) }}" class="btn btn-sm btn-info  mr-2"><i
                                        class="fa fa-pencil"></i> Edit</a>
                                {{--  <a href="{{ route('section.destroy', $section) }}" class="btn btn-sm
                                btn-danger">Delete</a>
                                --}}
                                <form method="post" action="{{ route('section.destroy', $section) }}"
                                    class="form-inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                                        onclick="return confirm('Are you sure you want to delete this item?');"> <i
                                            class="fa fa-trash"> </i> Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $sections->links() }}
                @endif
        </div>
    </div>



</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/section/show.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $section->title }}</h1>
        <a href="{{ route('section.edit', $section->id) }}" class="btn btn-sm btn-info shadow-sm ml-auto"><i
                class="fa fa-pencil"></i> Edit</a>
        <form method="post" action="{{ route('section.destroy', $section) }}" class="form-inline ml-2">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                onclick="return confirm('Are you sure you want to delete this item?');"> <i class="fa fa-trash"> </i>
                Delete</button>
        </form>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        @foreach ($questions as $question)
        <div class="col-md-3">
            <div class="question-part">
                <p><i class="fa fa-angle-double-right" aria-hidden="true"></i> {{ $question->title }}</p>
                <ol type='1'>
                    <li>{{ json_decode($question->options)[0] }}</li>
                    <li>{{ json_decode($question->options)[1] }}</li>
                    <li>{{ json_decode($question->options)[2] }}</li>
                    <li>{{ json_decode($question->options)[3] }}</li>
                </ol>

                <p><strong>Correct Answer: </strong>{{ implode(',',json_decode($question->answer)) }}</p>
            </div>
        </div>
        @endforeach
    </div>

</div>
<!-- /.container-fluid -->
@endsection