routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('dashboard'));
});

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('d/quiz', QuizController::class);

Route::resource('d/section', SectionController::class);

Route::resource('d/question', QuestionController::class);

app/Models/Quiz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Quiz extends Model
{
    use HasFactory;

    protected $table = 'quizess';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'title',
        'total_time',
        'total_mark',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function questions()
    {
        return $this->hasMany(Question::class, 'quiz_id')->with('quiz');
    }
    public function sections()
    {
        return $this->hasManyThrough(Question::class, Section::class);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quiz;
use App\Models\Section;
use App\Models\Question;
use Illuminate\Http\Request;


class QuizController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quizess = Quiz::paginate(20);
       return view('dashboard.quiz.index', [
           'quizess' => $quizess
       ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.quiz.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'title' => 'required|max:255',
            'total_time' => 'required|integer',
            'total_mark' => 'required|integer',
        ]);
        //create object and save
        $quiz = Quiz::create([
            'user_id' => auth()->user()->id,
            'title' => $request->title,
            'total_time' => $request->total_time,
            'total_mark' => $request->total_mark,
        ]);
        //set flash & redirect
        if($quiz){
            session()->flash('success', 'Quiz is successfully created!'); 
            return redirect(route('quiz.index'));
        }
        else{
            session()->flash('error', 'Failed to create quiz!'); 
            return redirect(route('quiz.create'));
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Quiz $quiz)
    {
        
        $values = $quiz->questions->groupBy('section_id')->toArray();
        if($values){
        $totalQuestions = $quiz->questions->count();
        $data = [];
       
        $sectionData = [];
        foreach ($values as $section_id => $value) {
            $section = Section::where('id', $section_id)->select('title')->first();
            $questionData = [];
            foreach($value as $question) {
                $singleQuestion = [
                    'title' => $question['title'],
                    'options' => json_decode($question['options']),
                    'answer' => json_decode($question['answer']),
                    'type' => $question['type']
                ];
                array_push($questionData, $singleQuestion);
            }
            $sectionData[$section->title] = $questionData;
        }
        $data = [
            'quiz' => $sectionData,
            'title' => $quiz->title,
            'total_mark' => $quiz->total_mark,
            'per_question_time' => ($quiz->total_time * 60) / $totalQuestions
        ];
        
        // dd($data);
        return view('dashboard.quiz.show', [
            'quiz' => $quiz,
            'data' => $data
        ]);
        }
        else{
            return view('dashboard.quiz.show', [
                'quiz' => $quiz,
                'data' => [
                    'quiz' => [],
                    'title' => $quiz->title,
                    'total_mark' => $quiz->total_mark,
                    'per_question_time' => 0
                ]
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Quiz $quiz)
    {
        return view('dashboard.quiz.edit', [
            'quiz' => $quiz
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Quiz $quiz)
    {
        //validation
        $request->validate([
            'title' => 'required|max:255',
            'total_time' => 'required|integer',
            'total_mark' => 'required|integer',
        ]);
        //update object and save
        $quiz->update([
                        'title' => $request->title,
                        'total_time' => $request->total_time,
                        'total_mark' => $request->total_mark
                    ]);

        //set flash & redirect
        if($quiz){
            session()->flash('success', 'Quiz is successfully updated!'); 
            return redirect(route('quiz.show', $quiz->id));
        }
        else{
            session()->flash('error', 'Failed to update quiz!'); 
            return redirect(route('quiz.edit', $quiz->id));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Quiz $quiz)
    {
        //delete quiz
        $quiz->delete();
        //set flash message
        session()->flash('success', 'Quiz is successfully deleted!'); 
        //redirect
        return redirect(route('quiz.index'));
    }
     
}

resources/views/dashboard/quiz/create.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add New Quiz</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-6 ">
            <div class="quiz-form">
                <form action="{{ route('quiz.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            quizInputTitle" name="title" value="{{ old('title') }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Total Time <small>(in minutes)</small></label>
                        <input class="form-control @error('total_time') is-invalid @enderror" id="quizInputTotalTime"
                            name="total_time" value="{{ old('total_time') }}">
                        @error('total_time')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Total Mark</label>
                        <input type="text" class="form-control @error('total_mark') is-invalid @enderror"
                            id="quizInputTotalmark" name="total_mark" value="{{ old('total_mark') }}">
                        @error('total_mark')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-primary">Create</button>


                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/quiz/edit.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit: {{ $quiz->title }}</h1>
    </div>
    @if (session()->has('error'))
    <div class="alert alert-warning">
        {{ session('error') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="quiz-form">
                <form action="{{ route('quiz.update', $quiz->id) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control @error('title') is-invalid @enderror" id="
                            quizInputTitle" name="title" value="{{ $quiz->title }}">
                        @error('title')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Total Time <small>in minutes</small></label>
                        <input type="text" class="form-control @error('total_time') is-invalid @enderror"
                            id="quizInputTotalTime" name="total_time" value="{{ $quiz->total_time }}">
                        @error('total_time')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Total Mark</label>
                        <input type="text" class="form-control @error('total_mark') is-invalid @enderror"
                            id="quizInputTotalMark" name="total_mark" value="{{ $quiz->total_mark }}">
                        @error('total_mark')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/quiz/index.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Quiz</h1>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            @if (count($quizess) <= 0) <p>No quiz found.</p>
                @else
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Total Time</th>
                            <th scope="col">Total Mark</th>
                            <th scope="col">Creator</th>
                            <th scope="col">Created At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($quizess as $index => $quiz)
                        <tr>
                            <th scope="row">{{ $index+1 }}</th>
                            <td>{{ $quiz->title }}</td>
                            <td>{{ $quiz->total_time }}</td>
                            <td>{{ $quiz->total_mark }}</td>
                            <td>{{ $quiz->creator->name }}</td>
                            <td>{{ date('F j, Y', strtotime($quiz->created_at)) }}</td>
                            <td class="d-flex">
                                <a href="{{ route('quiz.show', $quiz) }}" class="btn btn-sm btn-primary mr-2"><i
                                        class="fa fa-eye"></i> View</a>
                                <a href="{{ route('quiz.edit', $quiz) }}" class="btn btn-sm btn-info mr-2"><i
                                        class="fa fa-pencil"></i> Edit</a>
                                {{--  <a href="{{ route('quiz.destroy', $quiz) }}" class="btn btn-sm
                                btn-danger">Delete</a>
                                --}}
                                <form method="post" action="{{ route('quiz.destroy', $quiz) }}" class="form-inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                                        onclick="return confirm('Are you sure you want to delete this item?');"><i
                                            class="fa fa-trash"> </i> Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $quizess->links() }}
                @endif
        </div>
    </div>



</div>
<!-- /.container-fluid -->
@endsection

resources/views/dashboard/quiz/show.blade.php
@extends('layouts.admin')

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Quiz: {{ $quiz->title }}</h1>
        <a href="{{ route('quiz.edit', $quiz->id) }}" class="btn btn-sm btn-info shadow-sm ml-auto"><i
                class="fa fa-pencil"></i> Edit</a>
        <form method="post" action="{{ route('quiz.destroy', $quiz) }}" class="form-inline ml-2">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-sm btn-danger btn-flat show_confirm"
                onclick="return confirm('Are you sure you want to delete this item?');"> <i class="fa fa-trash"> </i>
                Delete</button>
        </form>
    </div>

    @if (session()->has('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
    @endif

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="quiz-content">
                <p><strong>Total Time:</strong> {{ $quiz->total_time }} Minutes</p>
                <p><strong>Total Mark:</strong> {{ $quiz->total_mark }}</p>
                <p><strong>Per Question Time:</strong> {{ ceil($data['per_question_time']) }} sec</p>
            </div>
        </div>
    </div>

    <div class='section-content'>
        @foreach ($data['quiz'] as $section => $questions)
        <div class="section-item">
            <h5 style="background: #ddd; padding: 5px 10px;">Section: {{ $section }}</h5>
            @foreach ($questions as $question)
            <div class="question-part">
                <p><i class="fa fa-angle-double-right" aria-hidden="true"></i> {{ $question['title'] }}</p>
                <ol type='1'>
                    <li>{{ $question['options'][0] }}</li>
                    <li>{{ $question['options'][1] }}</li>
                    <li>{{ $question['options'][2] }}</li>
                    <li>{{ $question['options'][3] }}</li>
                </ol>
                <p><strong>Correct Answer: </strong>{{ implode(',',$question['answer']) }}</p>
            </div>
            @endforeach
        </div>
        @endforeach
    </div>
</div>
<!-- /.container-fluid -->
@endsection